const CartActionTypes = {
    ADD_ITEM_TO_PURCHASE_ITEMS:"ADD_ITEM_TO_PURCHASE_ITEMS",
    ADD_ITEM_TO_RENT_ITEMS:"ADD_ITEM_TO_RENT_ITEMS",
    TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
}

export default CartActionTypes;