const CartActionTypes = {
    ADD_ITEM_TO_PURCHASE_ITEMS:"ADD_ITEM_TO_PURCHASE_ITEMS",
    ADD_ITEM_TO_RENT_ITEMS:"ADD_ITEM_TO_RENT_ITEMS",
    TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    CLEAR_CART:'CLEAR_CART',
    ADD_ITEM_TO_ITEMS:"ADD_ITEM_TO_ITEMS"
}

export default CartActionTypes;