const MovieActionTypes = {
    GET_ALL_FILMS:"GET_ALL_FILMS",
    GET_ALL_FILMS_START:"GET_ALL_FILMS_START",
    ERRORS:"ERRORS",
    GET_ALL_FILMS_SUCCESS:'GET_ALL_FILMS_SUCCESS',
    GET_ALL_FILMS_FAILURE:'GET_ALL_FILMS_FAILURE',
    GET_SINGLE_FILM_START:"GET_SINGLE_FILM_START",
    GET_SINGLE_FILM_START_SUCCESS:'GET_SINGLE_FILM_START_SUCCESS',
    GET_SINGLE_FILM_START_FAILURE:'GET_SINGLE_FILM_START_FAILURE',
}

export default MovieActionTypes;