const OrderActionTypes = {
    CREATE_ORDER_START:'CREATE_ORDER_START',
    CREATE_ORDER_SUCCESS:'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAILURE:'CREATE_ORDER_FAILURE',
    GET_ORDERS_START:'GET_ORDERS_START',
    GET_ORDERS_SUCCESS:'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE:'GET_ORDERS_FAILURE',
    GET_ORDER_BY_ID_START:'GET_ORDER_BY_ID_START',
    GET_ORDER_BY_ID_SUCCESS:'GET_ORDER_BY_ID_SUCCESS',
    GET_ORDER_BY_ID_FAILURE:'GET_ORDER_BY_ID_FAILURE',

}

export default OrderActionTypes;